import React from 'react';
import RebarXHero from '../components/rebarx/RebarXHero';
import Button from '../components/ui/Button';
import InteractiveFeatures from '../components/rebarx/InteractiveFeatures';
import CapabilitiesGrid from '../components/rebarx/CapabilitiesGrid';
import IntegrationHighlight from '../components/rebarx/IntegrationHighlight';
import Testimonial from '../components/rebarx/Testimonial';
import PricingSummary from '../components/rebarx/PricingSummary';
import FAQ from '../components/home/FAQ';

const rebarxFaqs = [
  {
    q: 'Do I need to own ETABS to use RebarX?',
    a: 'Yes, RebarX is designed as a post-processing detailing automation tool that relies on the internal forces generated by your ETABS model.'
  },
  {
    q: 'Does it support Eurocode and ACI?',
    a: 'Absolutely. RebarX has a comprehensive built-in code checking engine for ACI 318, Eurocode 2 (with regional annexes), and BS 8110.'
  },
  {
    q: 'What are the system requirements?',
    a: 'RebarX requires Windows 10/11 (64-bit), a modern multi-core processor (Intel i7 or AMD Ryzen 7 recommended), 16GB RAM minimum, and a dedicated GPU for large 3D model rendering.'
  },
  {
    q: 'How does network licensing work?',
    a: 'Enterprise licenses utilize a floating license manager. You can install RebarX on unlimited machines, and the server will grant access based on your total concurrent seat count.'
  }
];

const RebarX = () => {
  return (
    <main>
      <RebarXHero />
      <IntegrationHighlight />
      <InteractiveFeatures />
      <CapabilitiesGrid />
      <Testimonial />
      <PricingSummary />
      <FAQ faqsData={rebarxFaqs} />
    </main>
  );
};

export default RebarX;

